### ISSUE TITLE
"Entry point not found" when using GtkAda

### ISSUE THREAD

**Issue by rkoeninger** [AdaCore/gtkada#14]
I'm trying to use GtkAda in my GPS project. ([Repo](https://github.com/rkoeninger/life))

- Using the most recent freeware version (2017) of GNAT, GPS and GtkAda from the AdaCore website
- GNAT installed at: `C:\GNAT\2017`
- GtkAda installed at: `C:\GtkAda`
- Windows 10

GPS builds the project just fine with no sign of error.

When I try to run the project, the following 2 pop-ups appear and then the process exits with the status code `-1073741511`. No console output or any other sign of my code running.

```
The procedure entry point cairo_surface_create_similar_image could not be located in the dynamic link library C:\GtkAda\bin\libgdk-3-0.dll.
```
```
The procedure entry point atk_range_new could not be located in the dynamic link library C:\GtkAda\bin\libgtk-3-0.dll. 
```

This might be more of a problem with Gtk than GtkAda, or it's Windows-specific, but does anyone have any thoughts?

**Comment by rkoeninger** [comment]
This was a while ago, but I believe this was caused by a bad installation on Windows and was solved by re-installing.

**Comment by setton** [comment]
Ah, thanks for the update!
