### ISSUE TITLE
How to compile gtkada with Makefile

### ISSUE THREAD

**Issue by MarioBlunk** [AdaCore/gtkada#34]
Hello,
I'm not an expert with makefiles and need your help. As an alternative method to gprbuild (which works fine) I want to compile code by the traditional way with make. Reason: We can't expect all users of gtkada to have gprbuild installed.

The example Makefile here:

https://github.com/Blunk-electronic/ada_training/tree/master/src/gtkada_1

does not work. What must I do to get it working ?
Gtkada is well installed on the machine and compiling works well with gprbuild.

Thanks for your help.
Mario

**Comment by Fabien-Chouteau** [comment]
Hello @MarioBlunk,

>  Reason: We can't expect all users of gtkada to have gprbuild installed.

All the distributions of `GNAT` that I know of provide a `gprbuild`. Why are you saying that you can't expect users to have `gprbuild`?

>  As an alternative method to gprbuild (which works fine)

`gprbuild` is the supported build tool for our projects. It is possible to use `gprbuild` within a Makefile, like we do in some of our project. But using `gtkada` without `gprbuild` is not something we can help you with.

**Comment by TamaMcGlinn** [comment]
You may want to look at [the install instructions before they were simplified](https://github.com/AdaCore/gtkada/commit/300690dc273d4e15c3d91ced48d0274ee7ff9a5c); they seem to give more details and not require gprbuild.

**Comment by steve-cs** [comment]
@TamaMcGlinn, that's a dead end.  gtkada's Makefile.in requires gprbuild.

**Comment by MarioBlunk** [comment]
@Tama,
the link you posted is about installing gtkada itself. My idea is to compile ada code that uses the gtkada package without gprbuild. 

@all: It is more a theoretical question. No need to waste too much of your time with it.

**Comment by TamaMcGlinn** [comment]
The gitignore explicitly ignores all the Makefiles, which is bizarre; why would you want to do that? It seems that the instructions we need are in that file.

```
/Makefile
(...)
src/Makefile
src/gnome/Makefile
src/gtkextra/Makefile
src/opengl/Makefile
src/tools/Makefile
(...)
testgtk/Makefile
```

The readme for testgtk also still says to run make.

**Comment by setton** [comment]
@TamaMcGlinn the `Makefile` is generated during the configure step from `Makefile.in`.
