### ISSUE TITLE
Installation instructions for Windows need to be updated.

### ISSUE THREAD

**Issue by peter-milliken** [AdaCore/gtkada#36]
The INSTALL file appears to be out of date where it states:

"On Windows, just run the Gtkada installer and follow the displayed instructions."

There is no Gtkada installer visible anywhere in the repository (not that I can find). 

A google search for "GtkAda windows installer" led me to this thread: https://groups.google.com/g/comp.lang.ada/c/EYbZeeXLRcs?pli=1 where you can see various users stumble around until somebody locates a GtkAda binary in the Ada Core downloads (and even then the information is as confusing as hell, see my explanation below!). I have amended the thread with the information below, so the next poor sucker has some clue of where and what to do.

If you are attempting to perform a Windows installation of GNAT Ada, you INITIALLY find a binary at https://www.adacore.com/download - no mention of GtkAda on this page, the user happily downloads GNAT Ada and then starts looking for GtkAda (elsewhere) - finding it here at Github in a "broken" installation state. In the above-referenced thread, somebody pointed out there is a GtkAda install file in https://www.adacore.com/download/more (accessed by clicking the link "More packages, platforms, versions and sources »" on the page that contains the Windows GNAT Ada installation package. On the "more packages" page there is no sign of Gtkada in the dropdown. There is only "x86 Windows (64-bit)" in the dropdown and why would you select that? You have ALREADY installed GNAT Ada for Windows.

It is ONLY when you select "x86 Windows (64-bit)" (and WHY WOULD YOU? You have ALREADY downloaded the GNAT Ada install package!) that you are taken to a page that has the GNAT Ada package AND the GtkAda install package.

Hope this gets fixed - I'm amazed that the handful of people in the referenced thread happily continued with their lives with raising a ticket for this problem. It would have saved me considerable time.....

**Comment by setton** [comment]
Hello @peter-milliken, thank you for bringing this to our attention. GtkAda is available as well through the [Alire package manager](https://alire.ada.dev/), this is a good option for installing it easily.

**Comment by Fabien-Chouteau** [comment]
@peter-milliken if you want an example of GTKada project in [Alire](https://alire.ada.dev), you can try my `eagle_lander`.
Once you have Alire and a GNAT compiler in PATH, you can run:
```console
$ alr get eagle_lander
$ cd eagle_lander*
$ alr run
```

**Comment by peter-milliken** [comment]
Thanks for the tip about Alire,

I was not aware of it. It's been many years since I last used Ada and I
have lost track of developments in the Ada community. I'm retired now and
so I have some time to return to my favourite language.
