### ISSUE TITLE
gtk4

### ISSUE THREAD

**Issue by HROMANO** [AdaCore/gtkada#41]
Are there any plans for a gtk4 binding (in a forseable future)?

As a newcomer with Ada, Gtk seems the only viable portable and feature complete desktop gui for ada, but not really 'up to date'.

And thank you. Compared to rust syntax, Ada is so much more readable!

**Comment by berkeleynerd** [comment]
It's been more than a year so I hope this post isn't too much noise. In the intervening months have there been any updates to the roadmap with regard to Gtk 4?
