### ISSUE TITLE
libgtkada_gl ignore the DESTDIR setting during pacakge installation

### ISSUE THREAD

**Issue by qunying** [AdaCore/gtkada#5]
The latest release 17.0,  after compilation, the command
make DESTDIR=PKG_DIR install

Will install libgtkada_gl part into the system directory in stead of the DESTDIR specified in the command line.

This is because in Makefilie.in
```
105 ifeq (${HAVE_OPENGL}, True)
            ${GPRINSTALL_FULL} -XLIBRARY_TYPE=$(@F) --build-name=$(@F) \
                  --sources-subdir=include/gtkada/gtkada_gl.$(@F) \
                  --lib-subdir=${libdir}/gtkada/gtkada_gl.$(@F) \
                  --Psrc/opengl/gtkada_gl.gpr
110 endif
```

The lib-subdir is given an absolute directory without the DESTDIR being consider, it should be the same as other that use 
`--lib-subdir=lib/gtkada/gtkada_gl.$(@F) `
or
`-lib-subdir=${DESTDIR}${libdir}/gtkada/gtkada_gl.$(@F)`

**Comment by setton** [comment]
I agree. Would you like to make a pull request for this?

**Comment by setton** [comment]
Thank you for making the pull request! This is now merged.
